# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ahoy
tagline:             'Data-inspired'
description:         'Feel free to drop me suggesstions. You can find my contact info below in the About Me section.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eric Chuu
  url:               
  email:             

# Custom vars
version:             1.0.0

github:
repo:                https://github.com/echuu
